In [6]:
import gensim

In [7]:
from gensim.models import Word2Vec, KeyedVectors

In [8]:
import gensim.downloader as api

wv = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [9]:
wv.save("word2vec-google-news-300.gensim")

Pour charger:

wv = KeyedVectors.load("word2vec-google-news-300.gensim", mmap='r')

In [10]:
vec_king = wv["king"]

In [11]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [12]:
vec_king.shape

(300,)

In [13]:
wv.most_similar('rugby')

[('Rugby', 0.7643815279006958),
 ('Rugby_Union', 0.7332542538642883),
 ('Welsh_rugby', 0.732645571231842),
 ('Rugby_League', 0.6834455132484436),
 ('northern_hemisphere_rugby', 0.6832377314567566),
 ('All_Blacks', 0.6763246655464172),
 ('southern_hemisphere_rugby', 0.6645057201385498),
 ('RUGBY', 0.6614707112312317),
 ('Harlequins', 0.65956050157547),
 ('Bath_Rugby', 0.6554317474365234)]

In [14]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [15]:
wv.similarity("hockey","sports")

0.53541523

In [16]:
vec=wv["king"]-wv["man"]+wv["woman"]

In [17]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [18]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [170]:
import pandas as pd

import chardet

with open(r"C:\Users\nico_\Desktop\Data science bootcamp\NLP\spam.csv", "rb") as f:
    result = chardet.detect(f.read(100000))  # read first 100KB
    print(result)

{'encoding': 'Windows-1252', 'confidence': 0.7272080023536335, 'language': ''}


In [171]:
df = pd.read_csv(r"C:\Users\nico_\Desktop\Data science bootcamp\NLP\spam.csv", encoding='Windows-1252')

In [172]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [173]:
df.shape

(5572, 5)

In [174]:
df = df[["v1","v2"]]

df = df.rename(columns={"v1": "label", "v2": "message"})

In [175]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [176]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer # convertit le mot en sa forme canonique
import re

In [177]:
lemmatizer=WordNetLemmatizer()

In [178]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-z]',' ',df["message"][i]) # remplace tout caractère non alphabétique par un espace
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [179]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, df['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

Les caractères qui ne figurent pas dans '[^a-zA-z]'

Donc perte de 3 phrase du corpus pour la suite

map(len, corpus) applique len() à chaque élément de corpus

zip(...) assemble, pour chaque doc, un triplet :

i = longueur du doc (en caractères),

j = doc prétraité (de corpus),

k = message brut (de df['message']).

if i < 1 garde seulement les entrées où la longueur est 0 (docs vides).
Donc on obtient tous les documents vides sous la forme [0, doc_net, doc_brut].

In [180]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

## Liste of sentence, where each sentence is a list of tokens

In [181]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [182]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [183]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [184]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

## Training Word2vec from scratch

In [185]:
model=gensim.models.Word2Vec(words)

In [186]:
# To get all the vocabulary
model.wv.index_to_key      # model.wv vient du modèle Word2Vec que j'ai entraîné (gensim.models.Word2Vec). wv est l’objet KeyedVectors attaché au modèle, qui contient uniquement les vecteurs + vocabulaire (interface de lookup).

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'will',
 'ur',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'then',
 'am',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'need',
 'txt',
 'one',
 'today',
 'by',
 'going',
 'don',
 'home',
 'stop',
 'about',
 'she',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'dont',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'her',
 'any',
 'pls',
 'ha',
 'please',
 'co',
 'did',
 'msg',
 'been',
 'min',
 'some',
 'an',
 'make',
 'dear',
 'here',
 'night',
 'who',
 'message',
 'say',
 'well',
 're',
 'where',
 'thing',
 'much',
 'clai

In [187]:
model.corpus_count

5569

In [188]:
model.epochs

5

In [189]:
model.wv.similar_by_word('kid')

[('dear', 0.9966162443161011),
 ('nice', 0.9965949058532715),
 ('done', 0.9964191913604736),
 ('until', 0.9963740706443787),
 ('other', 0.9963550567626953),
 ('leh', 0.9963294863700867),
 ('im', 0.9963291883468628),
 ('life', 0.9963085651397705),
 ('dat', 0.9962664842605591),
 ('went', 0.9962629079818726)]

In [190]:
model.wv.most_similar('kid')

[('dear', 0.9966162443161011),
 ('nice', 0.9965949058532715),
 ('done', 0.9964191913604736),
 ('until', 0.9963740706443787),
 ('other', 0.9963550567626953),
 ('leh', 0.9963294863700867),
 ('im', 0.9963291883468628),
 ('life', 0.9963085651397705),
 ('dat', 0.9962664842605591),
 ('went', 0.9962629079818726)]

In [191]:
model.wv['good']

array([-0.274, 0.392, 0.266, 0.186, 0.139, -0.679, 0.236, 0.85, -0.268, -0.215, -0.151, -0.526, -0.0138, 0.161, 0.195, -0.18, 0.0732, -0.542, -0.0522, -0.737, 0.338, 0.304, 0.289, -0.332, 0.0375, 0.127, -0.321, -0.26, -0.361, 0.0224, 0.375, 0.0119, 0.233, -0.222, -0.179, 0.503, 0.0778, -0.323, -0.152, -0.68, 0.149, -0.261, -0.3, 0.0154, 0.269, -0.145, -0.293, -0.132, 0.0745, 0.233, 0.22, -0.291, -0.13, 0.0667, -0.109, 0.166, 0.208, 0.206, -0.463, 0.355, 0.0646, 0.0258, 0.0383, -0.141, -0.411, 0.412, 0.206, 0.256, -0.489, 0.403, -0.387, 0.285, 0.369, -0.204, 0.483, 0.194, -0.145, -0.232, -0.175, 0.178, -0.357, 0.114, -0.272, 0.603, -0.167, -0.11, 0.137, 0.428, 0.553, 0.0878, 0.455, 0.308, 0.0196, 0.253, 0.643, 0.335, 0.149, -0.122, 0.128, -0.0937], dtype=float32)

In [192]:
model.wv['good'].shape   # 100 vecteurs pour chaque mot car lors de l'entraînement du modèle, la nombre de vecteurs par défaut est 100

(100,)

## Vectors average for each sentence

In [193]:
import numpy as np

In [194]:
def avg_word2vec(doc):
    vecs = [model.wv.get_vector(w) for w in doc if w in model.wv.index_to_key]
    return np.mean(vecs, axis=0) if vecs else np.zeros(model.wv.vector_size, dtype=np.float32)
    #return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)

In [195]:
from tqdm import tqdm

In [196]:
# Apply fot the entire sentences
X=[]
for i in tqdm(range(len(words))):
    print(i)
    X.append(avg_word2vec(words[i]))

 42%|████▏     | 2352/5569 [00:00<00:00, 11630.88it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

 63%|██████▎   | 3516/5569 [00:00<00:00, 11083.27it/s]

2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551


100%|██████████| 5569/5569 [00:00<00:00, 11178.86it/s]

4644
4645
4646
4647
4648
4649
4650
4651
4652
4653
4654
4655
4656
4657
4658
4659
4660
4661
4662
4663
4664
4665
4666
4667
4668
4669
4670
4671
4672
4673
4674
4675
4676
4677
4678
4679
4680
4681
4682
4683
4684
4685
4686
4687
4688
4689
4690
4691
4692
4693
4694
4695
4696
4697
4698
4699
4700
4701
4702
4703
4704
4705
4706
4707
4708
4709
4710
4711
4712
4713
4714
4715
4716
4717
4718
4719
4720
4721
4722
4723
4724
4725
4726
4727
4728
4729
4730
4731
4732
4733
4734
4735
4736
4737
4738
4739
4740
4741
4742
4743
4744
4745
4746
4747
4748
4749
4750
4751
4752
4753
4754
4755
4756
4757
4758
4759
4760
4761
4762
4763
4764
4765
4766
4767
4768
4769
4770
4771
4772
4773
4774
4775
4776
4777
4778
4779
4780
4781
4782
4783
4784
4785
4786
4787
4788
4789
4790
4791
4792
4793
4794
4795
4796
4797
4798
4799
4800
4801
4802
4803
4804
4805
4806
4807
4808
4809
4810
4811
4812
4813
4814
4815
4816
4817
4818
4819
4820
4821
4822
4823
4824
4825
4826
4827
4828
4829
4830
4831
4832
4833
4834
4835
4836
4837
4838
4839
4840
4841
4842
4843


In [197]:
X

[array([-0.193, 0.292, 0.189, 0.146, 0.0912, -0.466, 0.144, 0.58, -0.213, -0.137, -0.125, -0.346, 0.00905, 0.113, 0.136, -0.133, 0.0479, -0.386, -0.0425, -0.524, 0.233, 0.193, 0.213, -0.218, 0.024, 0.11, -0.22, -0.173, -0.245, 0.0333, 0.238, 0.00372, 0.135, -0.161, -0.114, 0.362, 0.0448, -0.217, -0.115, -0.47, 0.0895, -0.192, -0.231, 0.0186, 0.181, -0.104, -0.195, -0.0926, 0.0604, 0.143, 0.139, -0.226, -0.0944, 0.0402, -0.0848, 0.116, 0.124, 0.13, -0.344, 0.253, 0.0477, 0.0184, 0.0426, -0.0972, -0.281, 0.296, 0.142, 0.189, -0.342, 0.282, -0.282, 0.182, 0.245, -0.156, 0.309, 0.151, -0.137, -0.145, -0.121, 0.111, -0.253, 0.0604, -0.201, 0.401, -0.0932, -0.0869, 0.0656, 0.302, 0.392, 0.0772, 0.347, 0.203, -0.00743, 0.166, 0.441, 0.213, 0.121, -0.102, 0.076, -0.053], dtype=float32),
 array([-0.179, 0.247, 0.158, 0.122, 0.0835, -0.393, 0.114, 0.494, -0.176, -0.118, -0.111, -0.292, 0.00703, 0.106, 0.114, -0.12, 0.0448, -0.336, -0.0446, -0.457, 0.203, 0.162, 0.176, -0.181, 0.0232, 0.0827, -0.

In [198]:
len(X)

5569

In [199]:
# Convert list in array, independent feature
X_new=np.array(X)

In [200]:
X_new

array([[-0.193, 0.292, 0.189, 0.146, 0.0912, -0.466, 0.144, 0.58, -0.213, -0.137, -0.125, -0.346, 0.00905, 0.113, 0.136, -0.133, 0.0479, -0.386, -0.0425, -0.524, 0.233, 0.193, 0.213, -0.218, 0.024, 0.11, -0.22, -0.173, -0.245, 0.0333, ..., -0.282, 0.182, 0.245, -0.156, 0.309, 0.151, -0.137, -0.145, -0.121, 0.111, -0.253, 0.0604, -0.201, 0.401, -0.0932, -0.0869, 0.0656, 0.302, 0.392, 0.0772, 0.347, 0.203, -0.00743, 0.166, 0.441, 0.213, 0.121, -0.102, 0.076, -0.053],
       [-0.179, 0.247, 0.158, 0.122, 0.0835, -0.393, 0.114, 0.494, -0.176, -0.118, -0.111, -0.292, 0.00703, 0.106, 0.114, -0.12, 0.0448, -0.336, -0.0446, -0.457, 0.203, 0.162, 0.176, -0.181, 0.0232, 0.0827, -0.189, -0.15, -0.208, 0.0276, ..., -0.233, 0.157, 0.213, -0.129, 0.265, 0.121, -0.117, -0.118, -0.108, 0.0815, -0.206, 0.0549, -0.179, 0.335, -0.083, -0.0692, 0.0529, 0.263, 0.33, 0.0567, 0.306, 0.166, -0.00214, 0.143, 0.366, 0.182, 0.106, -0.103, 0.0686, -0.0463],
       [-0.222, 0.313, 0.232, 0.193, 0.102, -0.512, 0.13

In [201]:
X_new.shape

(5569, 100)

In [202]:
# Dependent feature
y = df[list(map(lambda x: len(x)>0 , corpus))]   # On enlève les 3 phrases qui ne présentent pas de caratères
y=pd.get_dummies(y["label"],dtype=int)
y=y.iloc[:,0].values

In [203]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [222]:
y=pd.DataFrame(y)

In [223]:
y.head()

0
0  1
1  1
2  0
3  1
4  1

In [204]:
df.shape

(5572, 2)

Perte des éléments visibles:  5572 au départ pour 5569 ensuite

In [205]:
X[0].shape

(100,)

In [206]:
X[0].reshape(1,-1).shape # On veut 1 ligne avec les vecteurs pour colonne

(1, 100)

In [ ]:
# Final independent features
df=pd.DataFrame()
for i in range(0,len(X)):
    df=pd.concat([df, pd.DataFrame(X[i].reshape(1,-1))],ignore_index=True)  # X[i] a la forme (d,) (vecteur 1D), reshape(1, -1) le transforme en ligne 2D de forme (1, d)

In [208]:
df.shape

(5569, 100)

In [209]:
df.head()

0         1         2         3         4         5         6   \
0 -0.193397  0.291677  0.189429  0.145831  0.091219 -0.465649  0.144499   
1 -0.178571  0.247115  0.158456  0.122332  0.083451 -0.393356  0.113609   
2 -0.221869  0.313171  0.232174  0.192687  0.102342 -0.511977  0.135790   
3 -0.270992  0.386787  0.240024  0.186748  0.120864 -0.626247  0.186532   
4 -0.224597  0.321072  0.210416  0.155330  0.112433 -0.531370  0.158908   

         7         8         9   ...        90        91        92        93  \
0  0.579796 -0.213052 -0.136793  ...  0.347301  0.203372 -0.007432  0.165929   
1  0.493774 -0.176053 -0.117670  ...  0.306205  0.166025 -0.002135  0.143350   
2  0.619479 -0.276371 -0.139924  ...  0.377687  0.199539 -0.021800  0.172593   
3  0.788136 -0.267277 -0.186031  ...  0.467070  0.267744 -0.001470  0.238272   
4  0.668575 -0.236778 -0.165265  ...  0.389881  0.220418 -0.003399  0.198241   

         94        95        96        97        98        99  
0  0.441251  0.212669  0.120536 -0.102299  0.075955 -0.052980  
1  0.365884  0.181912  0.105536 -0.103005  0.068589 -0.046331  
2  0.448433  0.206015  0.123909 -0.114772  0.079802 -0.033369  
3  0.590921  0.289422  0.164449 -0.145412  0.097474 -0.068381  
4  0.496073  0.247260  0.128304 -0.134054  0.079437 -0.061898  

[5 rows x 100 columns]

In [210]:
# Independent feature
X=df

In [217]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [211]:
X.shape, y.shape

((5569, 100), (5569,))

In [224]:
# Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [225]:
from sklearn.ensemble import RandomForestClassifier

In [226]:
rf=RandomForestClassifier()

In [227]:
rf.fit(X_train,y_train)

c:\Users\nico_\anaconda3\envs\venvnlp\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [228]:
y_pred=rf.predict(X_test)

In [229]:
from sklearn.metrics import accuracy_score, classification_report

print("accuracy_score :",  accuracy_score(y_test,y_pred))
print("classification_report :", classification_report(y_test,y_pred))

accuracy_score : 0.9676840215439856
classification_report :               precision    recall  f1-score   support

           0       0.91      0.86      0.88       161
           1       0.98      0.99      0.98       953

    accuracy                           0.97      1114
   macro avg       0.95      0.92      0.93      1114
weighted avg       0.97      0.97      0.97      1114

